name=VQF_Arduino
version=1.0.1
author=LZQ
maintainer=LZQ
sentence=VQF sensor fusion with optional ICM20948 IMU reader
paragraph=Computes orientation via VQF, with NVS-based gyro bias persistence and accel calibration routine. (Can enable build-in ICM20948 reader, other IMU is not supported currently)
category=Sensors
url=https://github.com/LZQS1/VQF-for-Arduino
architectures=*
depends=Preferences
license=MIT
